FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app/ app/

ENV PYTHONPATH=/app
EXPOSE 8501

CMD ["streamlit", "run", "app/streamlit_app.py", "--server.port", "8502", "--server.address", "0.0.0.0"]
